name: CI
on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target=${{ matrix.target }}

      - name: copy amd64 binary
        run: cp target/${{ matrix.target }}/release/drone-portainer docker/drone-portainer-amd64
        if: matrix.target == 'x86_64-unknown-linux-musl'

      - name: copy arm64 binary
        run: cp target/${{ matrix.target }}/release/drone-portainer docker/drone-portainer-arm64
        if: matrix.target == 'aarch64-unknown-linux-musl'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          platforms: linux/arm64
          tags: ghcr.io/lginc/portainer-stack-deploy:latest
        if: matrix.target == 'aarch64-unknown-linux-musl'
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          platforms: linux/amd64
          tags: ghcr.io/lginc/portainer-stack-deploy:latest
        if: matrix.target == 'x86_64-unknown-linux-musl'